### ISSUE TITLE
How to use Visual Studio toolchain?

### ISSUE THREAD

**Issue by thbeu** [bblanchon/pdfium-binaries#141]
Thanks for this pretty useful build setup.

Is there any change to build with Visual Studio (2019) instead of the Clang toolchain. I tried https://github.com/bblanchon/pdfium-binaries/compare/master...thbeu:pdfium-binaries:build-md but did not succeed. Any help is appreciated. Thanks again.

**Comment by bblanchon** [comment]
Hi @thbeu,

[I updated the Windows runner](https://github.com/bblanchon/pdfium-binaries/commit/109e1cedaacd779b619f34ab020b1c15cf444957) because it came with Python 3.7, and PDFium needs Python 3.9+ to build or it produces the following error:

```
Traceback (most recent call last):
  File "D:/a/pdfium-binaries/pdfium-binaries/depot_tools/ninja.py", line 14, in <module>
    import gclient_paths
  File "D:\a\pdfium-binaries\pdfium-binaries\depot_tools\gclient_paths.py", line [24](https://github.com/bblanchon/pdfium-binaries/actions/runs/6452203565/job/17513883535#step:11:25), in <module>
    def FindGclientRoot(from_dir, filename='.gclient'):
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\functools.py", line 490, in lru_cache
    raise TypeError('Expected maxsize to be an integer or None')
TypeError: Expected maxsize to be an integer or None
```

If we manage to work around this error, we should be about to build with Visual Studio 2019.

BTW, the last build done with Visual Studio 2019 is [119.0.6043.0](https://github.com/bblanchon/pdfium-binaries/releases/tag/chromium%2F6043)

Best regards,
Benoit

**Comment by thbeu** [comment]
Thanks for the fast reply and the hint about the recently switched runner from windows-2019 to windows-2022.

I finally could [build](https://github.com/thbeu/pdfium-binaries/actions/runs/6738476146) 120.0.6097.0 with VS 2019 and /MD from my branch build-md, see https://github.com/bblanchon/pdfium-binaries/compare/master...thbeu:pdfium-binaries:build-md.
