### ISSUE TITLE
something wrong in Pdfium-android-arm.tgz for 32bit android

### ISSUE THREAD

**Issue by wish-rohitv** [bblanchon/pdfium-binaries#142]
hey guys, 
![image](https://github.com/bblanchon/pdfium-binaries/assets/126248971/37625b5e-f3a8-4bf4-9206-c451973ae0c2)
i have used `pdfium-android-arm.tgz` for cpu `arm` 32 bit android in my project 
and it giving me error -
![image](https://github.com/bblanchon/pdfium-binaries/assets/126248971/c8aa61d7-3490-4979-a91d-a80632975cf9)

i have did this multiple time i mean cross check but issue is not get fix
please help me

**Comment by bblanchon** [comment]
Hi @wish-rohitv,

```console
$ file libpdfium.so 
libpdfium.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[xxHash]=7bff048a1db54f4a, stripped
```

Looks 32-bit to me.

@mara004, did you see this?

Best regards,
Benoit

**Comment by wish-rohitv** [comment]
> Hi @wish-rohitv,
> 
> ```
> $ file libpdfium.so 
> libpdfium.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[xxHash]=7bff048a1db54f4a, stripped
> ```
> 
> Looks 32-bit to me.
> 
> @mara004, did you see this?
> 
> Best regards, Benoit

thanks for your time
yeah sir you are right and file is also showing 32 bit
![image](https://github.com/bblanchon/pdfium-binaries/assets/126248971/29f7fb18-9c54-43cd-ac3b-d192ed3b8e54)

then why i'm getting this error😟

**Comment by mara004** [comment]
I just came across this old thread incidentally. Sorry, I seem to have missed the ping back then.

If the output in https://github.com/bblanchon/pdfium-binaries/issues/142#issuecomment-1807020280 was really generated from the `pypdfium2_raw/libpdfium.so` binary in question, then I have no idea, as `file` clearly identifies it as 32-bit.

However, pypdfium2's setup didn't handle Android back then (it now does!), so I wonder how the OP installed pypdfium2? Since Python used to identify Android as Linux prior to PEP 738, our setup may have pulled in a Linux binary, which would fail. Did you manually replace the binary, or patch pypdfium2's setup?
