### ISSUE TITLE
SKIA Support 

### ISSUE THREAD

**Issue by hk9527** [bblanchon/pdfium-binaries#144]
I am developing on Windows and would like to study the RenderPDF With Skia options . Can you provide the pdfium library that supports SKIA ? Or any practical suggestions

**Comment by bblanchon** [comment]
Hi @hk9527,

The weekly build already compiles 39 versions of PDFium, which takes nearly 3 hours.
Adding support for Skia would mean adding 19 new variants (one for each supported target) and nearly double the build time.
I don't think it's worth it because support for Skia is still experimental, and I believe very few people would actually use these builds.

If you want to build PDFium yourself, you must set `pdf_use_skia = true`.
You could try to use my build scripts, but they are not portable (they don't need to be), so you should probably follow the official build instructions instead.

If you need to discuss this issue further, please continue the conversation on #29.

Best regards,
Benoit

**Comment by hk9527** [comment]
Thank You !
