### ISSUE TITLE
Windows x86 exported symbol names

### ISSUE THREAD

**Issue by alexisbg** [bblanchon/pdfium-binaries#16]
It seems to me there may be a problem with the symbol names exported by the x86 DLL. Running a "dumpbin /exports" on x64 and x86 DLLs prints different exported names.

Here is 3 examples of exported symbol names by x64 DLL:
`267  10A 0001A1FE FPDF_GetPageCount`
`275  112 00019CE8 FPDF_InitLibrary`
`278  115 00019D9F FPDF_LoadDocument`

They become on x86 DLL:
`267  10A 00016B70 _FPDF_GetPageCount@4`
`275  112 000166B8 _FPDF_InitLibrary@0`
`278  115 0001677C _FPDF_LoadDocument@8`

Linux .so exported names are identical to x64 DLL ones. Is is possible to remove "_" prefix and "@*" suffix from x86 DLL exported names ?

**Comment by bblanchon** [comment]
Hi @alexisbg,

This looks normal to me.
For x86, Visual Studio decorates the function name according to the calling convention.
For x64, it doesn't decorate names because there is only one calling convention.

See: https://docs.microsoft.com/en-us/cpp/build/reference/decorated-names?view=vs-2017

Regards,
Benoit
