### ISSUE TITLE
Can you make for iOS?

### ISSUE THREAD

**Issue by paulo-coutinho** [bblanchon/pdfium-binaries#4]
Nice project.

Can you make for iOS?

Thanks.

**Comment by prsolucoes** [comment]
Hi,

I finished my script to build the PDFium to iOS. All is here with manual patchs:
https://github.com/prsolucoes/mobile-pdfium

But i have some issues after compile. All issues is described here:
https://github.com/prsolucoes/mobile-pdfium/issues/1

Can you help me?

**Comment by Changzw** [comment]
……  I have to download chrome source code that is so huge that I don't know how long to get libpdfium.a

**Comment by sunwicked** [comment]
Any thoughts for Android?

**Comment by winstonschen** [comment]
I would like to set up Xcode or create a script in order to compile libpdfium.a for iOS. I need to do this because I need it to work with iOS and soon Catalyst which makes iOS apps run on Macs. There is also an issue with PDFium (how it handles hyphens) which I would like to modify.

I’m the developer of Voice Dream Reader, an iOS app used primarily by blind people. And I would like pay someone to help me set this up. If you're interested, please email me at winston@voicedream.com.

Thanks!
