### ISSUE TITLE
Linux Arm32 target

### ISSUE THREAD

**Issue by ChristofferGreen** [bblanchon/pdfium-binaries#46]
Hi!

I have sucessfully built a Linux Arm 32-bit target within x86 Ubuntu and run on a raspbian based raspberry pi (within the manga reader app Kavita) by using the pdfium-binaries build files and setting CPU to arm (and downloading the Arm image). I was wondering if it would be a good idea to submit a pull request that adds such a target?

If so the way to do it I guess would be to modify the .travis.yml file and add a new matrix element (linux, TARGET_CPU=arm) as well as the appveyor.yml file by adding a new 'arm' platform? 

The use case is as written above, adding pdf functionality to Kavita on raspberry pi.

Any thoughts? Thank you

Br/ Christoffer

**Comment by bblanchon** [comment]
Hi Christopher,

This sounds like an excellent idea!
Please open a PR but only modify `travis.yml` (I use only AppVeyor for Windows builds).
Don't add the V8 build because I'll run out of Travis credit again.

Best regards,
Benoit

**Comment by ChristofferGreen** [comment]
Ah, that's great. One thing I am a bit confused about is the image selection. To compile on my local ubuntu I had to manually install an arm image (the build process stopped and told me to do that, but worked after I installed it), I see the osx builds in the travis file have an image command but I do not know if that is relevant. Can I expect the arm image to already be installed in the travis system?

**Comment by bblanchon** [comment]
The ARM toolchain isn't installed on the Travis builder, but you can install it by adding the following lines in the build matrix:

```yaml
- addons:
    apt:
      packages: ['g++-arm-linux-gnueabihf']
```

Then, you must use `arm-linux-gnueabihf-gcc` and `arm-linux-gnueabihf-g++` instead of `gcc` and `g++`.
Hopefully, they will be automatically picked up after setting `target_cpu` to the right value; if not, you make need to add environment variables.

For reference, [here is a Travis configuration](https://github.com/bblanchon/ArduinoJson/blob/v6.17.2/.travis.yml#L55-L58) that I used to build ArduinoJson for Raspberry Pi. Note that I used `_CC` instead of the standard of `CC` because Travis overrides it (and the same goes for `CXX`).
