### ISSUE TITLE
[Question] License for patches?

### ISSUE THREAD

**Issue by mara004** [bblanchon/pdfium-binaries#55]
Hello,

I'm currently trying to make my repository, [`pypdfium2`](https://github.com/pypdfium2-team/pypdfium2), compliant with the [`reuse`](https://reuse.software/) standard. As I also need to build PDFium, I have incorporated most of the patches from this repository. May I ask under which license you would provide them?
In general, could you please add a license file for the whole repository?

(This question also addresses @BoLaMN as I have the `gclient_scm` patch, too)

Many thanks!

**Comment by mara004** [comment]
@bblanchon

**Comment by bblanchon** [comment]
Hi @mara004,

Please apologize for the late response, I originally misread your message and thought you only wanted to reuse the PR from @BoLaMN.

I didn't put a license file in the repository because I feared that people would think it applies to PDFium as well.
Anyway, feel free to reuse the patches in your repository.
However, I would greatly appreciate it if you mention this repository as the origin of these patches.

Let me know if you need anything else.

Best regards,
Benoit

**Comment by mara004** [comment]
Thanks for your reply!
I understand your concern that people might think it's the PDFium license. However, maybe it could be clarified somehow that this is not the case (e. g. by naming the license file `LICENSE_BuildScripts.txt`, or by adding a note to the readme).
For now, I have added you and @BoLaMN as author of the patches in [`.reuse/dep5`](https://github.com/pypdfium2-team/pypdfium2/blob/main/.reuse/dep5).
