### ISSUE TITLE
pack with v8

### ISSUE THREAD

**Issue by vesio** [bblanchon/pdfium-binaries#58]
steps/07-pack.sh

```
CFG=${CONFIGURATION:-Release}
V8=${V8:-disabled} 
OS=${PDFium_TARGET_OS:?}
CPU=${PDFium_TARGET_CPU:?}
VERSION=${PDFium_VERSION:-}
PATCHES="$PWD/patches"

STAGING="$PWD/staging"
SOURCE=${PDFium_SOURCE_DIR:-pdfium}
BUILD=${PDFium_BUILD_DIR:-pdfium/out}
```
the second line V8 value is not from build.sh
why not use `V8=${PDFium_V8:-disabled}`

there is PDFium_V8 config in the build.sh
```
#!/usr/bin/env bash
#
# Variables to provide:
# CONFIGURATION = Debug | Release
# PDFium_TARGET_CPU = x86 | x64 | arm | arm64
# PDFium_TARGET_OS = mac | linux | win
# PDFium_BRANCH = main | chromium/3211 | ...
# PDFium_V8 = enabled
```

**Comment by bblanchon** [comment]
Good catch!
I have to admit, I didn't run any V8 build since I migrated to GitHub Actions.

Right now, I'm focusing on the [iOS build](https://github.com/bblanchon/pdfium-binaries/tree/ios) but I'm facing [an issue with CMake](https://discourse.cmake.org/t/find-package-stops-working-when-cmake-system-name-ios/4609).
I expect to restore the V8 builds once every non-v8 works fine.
