### ISSUE TITLE
Github Marked "Latest" Release 

### ISSUE THREAD

**Issue by DJGosnell** [bblanchon/pdfium-binaries#60]
Currently, the previous release of [PDFium 99.0.4763.0](https://github.com/bblanchon/pdfium-binaries/releases/tag/chromium%2F4763) is marked as the "Latest" release instead of the actual newest build of[PDFium 99.0.4777.0](https://github.com/bblanchon/pdfium-binaries/releases/tag/chromium%2F4777)

This causes the links on the main `readme.md` to link to the older release instead of the actual latest.

I also run another [library](https://github.com/Dtronix/PDFiumCore) which takes the "latest" build and generates .NET bindings for certain platforms and this change in the indicated "latest" release also is also affecting my current build process.

**Comment by bblanchon** [comment]
Thanks, @DJGosnell; I was not aware of this problem.

According to [this conversation](https://github.community/t/latest-release-isnt-the-real-latest/2244/6), it seems that GitHub uses the date of the commit to determine which the latest release.
In my case, several releases can point to the same commit (via different tags), which could explain why the order is wrong.
However, I looked at older releases, and it seems only 4777 is out of order, so maybe that was just a hiccup.

Let's see if this happens again.
If so, I'll try to create an annotated tag (instead of a lightweight tag) so it has a date.

Best regards,
Benoit

**Comment by DJGosnell** [comment]
It is now working with the latest build.  I'll reopen this issue if I see it being an issue at a later time,
