### ISSUE TITLE
PDFium binaries for debug projects

### ISSUE THREAD

**Issue by aimi617** [bblanchon/pdfium-binaries#73]
Where can I download latest C++ PDFium binaries for debug projects? As I understand all latest binaries for Release only.

**Comment by bblanchon** [comment]
Hi @aimi617,

I used to distribute Debug builds, but the build times were really long, and nobody used them.
Why don't you use the Release build?
If you need to debug the code inside PDFium, you're probably better off compiling the library yourself.

Best regards,
Benoit

**Comment by aimi617** [comment]
I need to debug the codes of my proprietary project (not PDFium) working with acrofields, that's why I need PDFium debug .dll with .lib. I cannot use Release binaries to trace my codes.

**Comment by bblanchon** [comment]
I'm not sure restoring the debug builds is wise, but I'll leave this issue open to see how many people request it.
Meanwhile, please try [version 4005](https://github.com/bblanchon/pdfium-binaries/releases/tag/chromium%2F4005), which is the latest to have the debug build.

**Comment by aimi617** [comment]
Thanks, I'll test that build.

**Comment by fredemmott** [comment]
One possibility would be to build release-with-debug-symbols, and distribute the debug symbols separately?

That said, my exceptions turned out to be all be one of two things:
- not calling `FPDF_InitLibrary()`
- pdfium is absolutely not threadsafe, even if working with different FPDFDOCUMENTs in different files

**Comment by bblanchon** [comment]
I'm closing this issue because I don't think I'll ever add the debug builds.
The release builds are already taking more than 3 hours (32 hours of CPU time), so I cannot imagine how long it would take to add the debug builds.
Note that my [`build.sh`](https://github.com/bblanchon/pdfium-binaries/blob/master/build.sh) support a `-d` flag to compile in debug mode, so it shouldn't be too hard to build it yourself.
